[package]
name = "scribe-parser"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = 3

[dependencies]
ir = { path = "../ir" }
zetaruntime = { path = "../zeta_utilities" }
smallvec = "2.0.0-alpha.12"
ctrc-graph = { path = "../ctrc-graph" }