[package]
name = "engraver-assembly-emit"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = 3

[dependencies]
thiserror = "2.0.12"
seahash = "4.1.0"
ir = { path = "../ir" }
leapfrog = "0.3.2"
parking_lot = "0.12.4"
cranelift = "0.125.3"
cranelift-module = "0.125.3"
cranelift-codegen = "0.125.3"
cranelift-object = "0.125.3"
cranelift-frontend = "0.125.3"
smallvec = "1.15.0"
zetaruntime = { path = "../zeta_utilities" }