[package]
name = "ir"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = 3

[dependencies]
thiserror = "2.0.16"
fxhash = "0.2.1"
zetaruntime = { path = "../zeta_utilities" }
smallvec = "2.0.0-alpha.12"
is-terminal = "0.4.17"
owo-colors = "4.2.3"

[dev-dependencies]
rstest = "0.26.1"
