
[package]
name = "emberforge-compiler"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = 3

[dependencies]
zetaruntime = { path = "../zeta_utilities" }
ir = { path = "../ir" }
smallvec = "2.0.0-alpha.12"
arrayvec = "0.7.6"